import type { BoligFixture, Place } from "@/lib/prototype/bolig/contract";
import { BOLIG_WALK_MINUTES } from "@/lib/prototype/bolig/travel-times";

/**
 * Demoverden for bruktbolig-prototypen: én FIKTIV enebolig på Ranheim i
 * Trondheim, omgitt av EKTE steder fra Placys stedsdatabase (v2.pois) med
 * kilder og kontrolldato. Selgersitater er fiktive og merkes «Eksempeldata».
 *
 * Regler:
 * - Ingen oppdiktede URL-er. `url` bare når den er kontrollert.
 * - «documented» krever minst én kilde og en `checkedAt`.
 * - Skolekrets, opptak, rutetilbud og åpningstider påstås ikke uten grunnlag.
 * - Gangtider er målt (Mapbox Directions) fra eksempelboligens punkt.
 */

/** Steder før gangtid er koblet på (se BOLIG_FIXTURE.places nederst). */
const RAW_PLACES: Place[] = [
  /* ---------- Dagligvare ---------- */
  {
    id: "google-ChIJJwBGaw4xbUYR6rZG77PA19k",
    name: "REMA 1000 Ranheimsfjæra",
    kind: "Dagligvare",
    topics: ["dagligvare"],
    lat: 63.4287887,
    lng: 10.5271202,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Ranheimsfjæra 49, Ranheim",
    website: "https://rema.no/",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJJwBGaw4xbUYR6rZG77PA19k",
    openingHours: [
      "mandag: 07:00–23:00",
      "tirsdag: 07:00–23:00",
      "onsdag: 07:00–23:00",
      "torsdag: 07:00–23:00",
      "fredag: 07:00–23:00",
      "lørdag: 07:00–23:00",
      "søndag: Stengt",
    ],
    facts: [
      { id: "rema-f1", text: "REMA 1000 Ranheimsfjæra er en dagligvarebutikk i REMA 1000-kjeden, med adresse Ranheimsfjæra 49.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-08-24" },
      { id: "rema-f2", text: "Har fått 98 vurderinger på Google, med snittscore 4 av 5.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-08-24" },
    ],
  },
  {
    id: "google-ChIJNe4i_4owbUYRaRRfP1vXeEA",
    name: "Extra Grilstad",
    kind: "Dagligvare",
    topics: ["dagligvare"],
    lat: 63.4339964,
    lng: 10.5038036,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Skonnertvegen 8, Ranheim",
    website: "https://www.coop.no/butikker/extra/extra-grilstad-2502",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJNe4i_4owbUYRaRRfP1vXeEA",
    openingHours: [
      "mandag: 07:00–23:00",
      "tirsdag: 07:00–23:00",
      "onsdag: 07:00–23:00",
      "torsdag: 07:00–23:00",
      "fredag: 07:00–23:00",
      "lørdag: 07:00–23:00",
      "søndag: 10:00–22:00",
    ],
    facts: [
      { id: "extra-grilstad-f1", text: "Extra Grilstad er en dagligvarebutikk i Coop-kjeden Extra, med adresse Skonnertvegen 8.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
      { id: "extra-grilstad-f2", text: "Handleturen har utsikt mot fjorden, og butikken har godt parkeringstilbud, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
    ],
  },
  {
    id: "google-ChIJrSNSbnkwbUYRS6a-0KZx9mI",
    name: "Coop Prix Olderdalen",
    kind: "Dagligvare",
    topics: ["dagligvare"],
    lat: 63.4216035,
    lng: 10.5265768,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Sverre Svendsens veg 8, Ranheim",
    website: "https://www.coop.no/butikker/coop-prix/coop-prix-olderdalen-1808",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJrSNSbnkwbUYRS6a-0KZx9mI",
    image: { src: "https://lh3.googleusercontent.com/place-photos/AJRVUZNc3gFQ6VLLXAbRMVfwiZsSBUo5WtxYSz8dOsR-kKQv_IAx0o3rRVEOsT81zf-w5jMFvG5vjjSS2tppom-yb-uF8TJq1x5b1uzaOwwv7brED5OwzbqPs1ivl7TgsQzlDxuCD4DsJua7ksITDQ=s4800-w720", alt: "Coop Prix Olderdalen", kind: "photo", credit: "Google" },
    openingHours: [
      "mandag: 07:00–23:00",
      "tirsdag: 07:00–23:00",
      "onsdag: 07:00–23:00",
      "torsdag: 07:00–23:00",
      "fredag: 07:00–23:00",
      "lørdag: 08:00–22:00",
      "søndag: Stengt",
    ],
    facts: [
      { id: "coop-prix-f1", text: "Coop Prix Olderdalen er nærbutikken for den daglige handelen, med kompakt utvalg og kort vei.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "coop-prix-f2", text: "Praktisk for småhandel, og nærmere enn de store butikkene i bydelen, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "google-ChIJsZDEHsAxbUYRW2W4iQwcdWU",
    name: "Rosenborg Bakeri",
    kind: "Bakeri",
    topics: ["dagligvare", "mat"],
    lat: 63.4290341,
    lng: 10.5272308,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Ranheimsfjæra 47, Ranheim",
    website: "https://www.rosenborgbakeri.no/",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJsZDEHsAxbUYRW2W4iQwcdWU",
    image: { src: "https://lh3.googleusercontent.com/place-photos/AJRVUZOqwAvS42HcT0tOweBiSAk84Vm8t1XkIjGZ9ipXcxVA7mTiaUD9QQ3WrHMIraUSZKBNf6B3PmHu2ElJVQVWn-L99pS2cumpoB5wxq0AusrmDADIX36SPCmKq5ygNA9x6UKp6KnvgkyC1gC7R3U=s4800-w800", alt: "Rosenborg Bakeri", kind: "photo", credit: "Google" },
    openingHours: [
      "mandag: 08:00–18:00",
      "tirsdag: 08:00–18:00",
      "onsdag: 08:00–18:00",
      "torsdag: 08:00–18:00",
      "fredag: 08:00–18:00",
      "lørdag: 09:00–17:00",
      "søndag: 09:00–16:00",
    ],
    facts: [
      { id: "rosenborg-bakeri-f1", text: "Rosenborg Bakeri på Grilstad tilbyr ferskt brød og bakevarer fra byens kjente bakeri.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "rosenborg-bakeri-f2", text: "Fast stopp for ferskt brød, og populært blant beboere i hele bydelen, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "google-ChIJRTCl-IowbUYRFcNuL7_vqUQ",
    name: "Vitusapotek Ranheim",
    kind: "Apotek",
    topics: ["dagligvare"],
    lat: 63.4341625,
    lng: 10.5028887,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Skonnertvegen 8, Ranheim",
    website: "https://www.vitusapotek.no/apotek/trondelag/ranheim/vitusapotek-ranheim?utm_source=google&utm_medium=organic&utm_id=gmb&utm_content=main_button",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJRTCl-IowbUYRFcNuL7_vqUQ",
    openingHours: [
      "mandag: 09:00–18:00",
      "tirsdag: 09:00–18:00",
      "onsdag: 09:00–18:00",
      "torsdag: 09:00–18:00",
      "fredag: 09:00–18:00",
      "lørdag: 09:00–16:00",
      "søndag: Stengt",
    ],
    facts: [
      { id: "vitusapotek-f1", text: "Vitusapotek Ranheim dekker hverdagsbehovene for medisin og helseprodukter i bydelen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
      { id: "vitusapotek-f2", text: "Apotek i Vitusapotek-kjeden, med adresse Skonnertvegen 8.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
    ],
  },
  {
    id: "osm-node-6013240435",
    name: "Ranheim post i butikk",
    kind: "Post i butikk",
    topics: ["dagligvare"],
    lat: 63.4339289,
    lng: 10.5034997,
    provenance: "documented",
    sourceIds: ["src-osm"],
    facts: [
      { id: "ranheim-post-f1", text: "Ranheim post i butikk tilbyr posttjenester i tilknytning til en butikk på Ranheim.", provenance: "documented", sourceIds: ["src-osm"], checkedAt: "2026-08-14" },
      { id: "ranheim-post-f2", text: "Registrert som posttjeneste i OpenStreetMap.", provenance: "documented", sourceIds: ["src-osm"], checkedAt: "2026-08-14" },
    ],
  },

  /* ---------- Barn og oppvekst ---------- */
  {
    id: "7a3f2a06-4fa0-401a-aef5-f686ddf62988",
    name: "Ranheim skole",
    kind: "Barneskole",
    topics: ["barn"],
    lat: 63.42996,
    lng: 10.52283,
    provenance: "documented",
    sourceIds: ["src-nsr", "src-placy-pool"],
    facts: [
      { id: "ranheim-skole-f1", text: "Offentlig grunnskole registrert i Nasjonalt skoleregister.", provenance: "documented", sourceIds: ["src-nsr"], checkedAt: "2026-06-10" },
      { id: "ranheim-skole-f2", text: "Trygg skolevei gjennom etablert boligområde ved Ranheim sentrum, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "2ca80341-b2cc-428e-96af-8916292a3e27",
    name: "Charlottenlund ungdomsskole",
    kind: "Ungdomsskole",
    topics: ["barn"],
    lat: 63.42664,
    lng: 10.48948,
    provenance: "documented",
    sourceIds: ["src-nsr", "src-placy-pool"],
    facts: [
      { id: "charlottenlund-us-f1", text: "Offentlig grunnskole registrert i Nasjonalt skoleregister.", provenance: "documented", sourceIds: ["src-nsr"], checkedAt: "2026-04-17" },
      { id: "charlottenlund-us-f2", text: "Ungdomsskole for elever fra Charlottenlund-området, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "0347363d-479f-4f96-8999-51a4279aa594",
    name: "Grilstad Fus barnehage AS",
    kind: "Barnehage",
    topics: ["barn"],
    lat: 63.43045,
    lng: 10.50501,
    provenance: "documented",
    sourceIds: ["src-barnehagefakta", "src-placy-pool"],
    facts: [
      { id: "grilstad-fus-bhg-f1", text: "Registrert i Barnehagefakta.", provenance: "documented", sourceIds: ["src-barnehagefakta"], checkedAt: "2026-06-11" },
      { id: "grilstad-fus-bhg-f2", text: "Barnehage i Fus-kjeden på Ranheim.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-11" },
    ],
  },
  {
    id: "2aa32541-6473-4e11-a3d9-4b075779cee7",
    name: "Grillstadfjæra barnehage",
    kind: "Barnehage",
    topics: ["barn"],
    lat: 63.43583,
    lng: 10.50298,
    provenance: "documented",
    sourceIds: ["src-barnehagefakta", "src-placy-pool"],
    facts: [
      { id: "grillstadfjaera-bhg-f1", text: "Kommunal barnehage for barn 1–5 år, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-11" },
      { id: "grillstadfjaera-bhg-f2", text: "Registrert i Barnehagefakta.", provenance: "documented", sourceIds: ["src-barnehagefakta"], checkedAt: "2026-06-11" },
    ],
  },
  {
    id: "d6ab206e-3340-42eb-b67d-a7f1f7a2b2a2",
    name: "Sjøskogbekken Fus barnehage AS",
    kind: "Barnehage",
    topics: ["barn"],
    lat: 63.42694,
    lng: 10.52284,
    provenance: "documented",
    sourceIds: ["src-barnehagefakta", "src-placy-pool"],
    facts: [
      { id: "sjoskogbekken-bhg-f1", text: "Privat barnehage for barn 1–5 år, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "sjoskogbekken-bhg-f2", text: "Registrert i Barnehagefakta.", provenance: "documented", sourceIds: ["src-barnehagefakta"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "6657eda5-23d3-4f6f-936f-70cd2ef53399",
    name: "Ranheimsfjæra barnehage",
    kind: "Barnehage",
    topics: ["barn"],
    lat: 63.429,
    lng: 10.53108,
    provenance: "documented",
    sourceIds: ["src-barnehagefakta", "src-placy-pool"],
    facts: [
      { id: "ranheimsfjaera-bhg-f1", text: "Kommunal barnehage for barn 1–5 år, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "ranheimsfjaera-bhg-f2", text: "Registrert i Barnehagefakta.", provenance: "documented", sourceIds: ["src-barnehagefakta"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "lekeplass-hulderveien-lek",
    name: "Hulderveien lek",
    kind: "Lekeplass",
    topics: ["barn"],
    lat: 63.428460108,
    lng: 10.513203612,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    facts: [
      { id: "hulderveien-lek-f1", text: "Hulderveien lek er en av flere lekeplasser i nabolaget.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "hulderveien-lek-f2", text: "Trygt lekeområde for barn i bydelen, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "lekeplass-grillstadfj-ra-lek",
    name: "Grillstadfjæra lek",
    kind: "Lekeplass",
    topics: ["barn"],
    lat: 63.43630042,
    lng: 10.5046589925,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    facts: [
      { id: "grillstadfjaera-lek-f1", text: "Grillstadfjæra lek er en av flere lekeplasser i nabolaget.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "grillstadfjaera-lek-f2", text: "Trygt lekeområde for barn i bydelen, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "osm-way-84078489",
    name: "Ranheimshallen",
    kind: "Idrettshall",
    topics: ["barn"],
    lat: 63.42876,
    lng: 10.522812,
    provenance: "documented",
    sourceIds: ["src-osm"],
    facts: [
      { id: "ranheimshallen-f1", text: "Ranheimshallen er bydelens idrettshall med plass til flere idretter.", provenance: "documented", sourceIds: ["src-osm"], checkedAt: "2026-04-17" },
      { id: "ranheimshallen-f2", text: "Brukes til håndball, turn og innendørs fotball, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-osm"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "osm-way-84078488",
    name: "Ranheim idrettsanlegg",
    kind: "Idrettsanlegg",
    topics: ["barn"],
    lat: 63.4279173,
    lng: 10.5265199,
    provenance: "documented",
    sourceIds: ["src-osm"],
    facts: [
      { id: "ranheim-idrettsanlegg-f1", text: "Ranheim idrettsanlegg har kunstgressbane og friidrettsbane.", provenance: "documented", sourceIds: ["src-osm"], checkedAt: "2026-04-17" },
      { id: "ranheim-idrettsanlegg-f2", text: "Åpent for organisert idrett og egentrening, rett ved Extra Arena, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-osm"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "google-ChIJV82_lH0wbUYRKfodIclrdCY",
    name: "Trondheim folkebibliotek Ranheim",
    kind: "Bibliotek",
    topics: ["barn"],
    lat: 63.4278063,
    lng: 10.5250222,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Ranheimsvegen 172, Ranheim",
    website: "http://www.tfb.no/",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJV82_lH0wbUYRKfodIclrdCY",
    openingHours: [
      "mandag: 10:00–16:00",
      "tirsdag: 10:00–16:00",
      "onsdag: 10:00–19:00",
      "torsdag: 10:00–16:00",
      "fredag: 10:00–16:00",
      "lørdag: 10:00–14:00",
      "søndag: Stengt",
    ],
    facts: [
      { id: "folkebibliotek-f1", text: "Trondheim folkebibliotek Ranheim er bydelens bibliotekfilial med aktiviteter for barn og voksne.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
      { id: "folkebibliotek-f2", text: "Ligger i Ranheimsvegen 172, sammen med Kulturtribunen på Ranheim.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
    ],
  },
  {
    id: "google-ChIJ9YfOuH0wbUYRnpyiF-UWio4",
    name: "Kulturtribunen på Ranheim",
    kind: "Kulturhus",
    topics: ["barn"],
    lat: 63.4279643,
    lng: 10.5249457,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Ranheimsvegen 172, Ranheim",
    website: "https://biblioteket.trondheim.kommune.no/",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ9YfOuH0wbUYRnpyiF-UWio4",
    openingHours: [
      "mandag: 10:00–16:00",
      "tirsdag: 10:00–16:00",
      "onsdag: 10:00–19:00",
      "torsdag: 10:00–16:00",
      "fredag: 10:00–16:00",
      "lørdag: 10:00–14:00",
      "søndag: Stengt",
    ],
    facts: [
      { id: "kulturtribunen-f1", text: "Kulturtribunen på Ranheim er et kulturhus med arrangementer og aktiviteter for bydelen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
      { id: "kulturtribunen-f2", text: "Tilbyr konserter, foredrag og utstillinger, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
    ],
  },
  {
    id: "google-ChIJ8QQ3630wbUYRUMm48wRgbVc",
    name: "3T-Ranheim",
    kind: "Treningssenter",
    topics: ["barn"],
    lat: 63.4280825,
    lng: 10.5251726,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Ranheim Arena, Ranheimsvegen 174, Ranheim",
    website: "https://www.3t.no/treningssenter/3t-ranheim",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ8QQ3630wbUYRUMm48wRgbVc",
    openingHours: [
      "mandag: 05:00–00:00",
      "tirsdag: 05:00–00:00",
      "onsdag: 05:00–00:00",
      "torsdag: 05:00–00:00",
      "fredag: 05:00–00:00",
      "lørdag: 05:00–00:00",
      "søndag: 05:00–00:00",
    ],
    facts: [
      { id: "3t-ranheim-f1", text: "3T-Ranheim er et av kjedens moderne treningssentre, i tribuneanlegget ved Extra Arena.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
      { id: "3t-ranheim-f2", text: "Tilbyr gruppetimer, styrke og yoga, med gratis parkering.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
    ],
  },

  /* ---------- Tur og natur ---------- */
  {
    id: "badeplass-grilstadstranda",
    name: "Grilstadstranda",
    kind: "Badeplass",
    topics: ["natur"],
    lat: 63.43615536217392,
    lng: 10.513102194347827,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    facts: [
      { id: "grilstadstranda-f1", text: "Grilstadstranda er en populær badeplass langs Trondheimsfjorden.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "grilstadstranda-f2", text: "Del av strandlinjen som binder sammen badeplassene på Ranheim.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "badeplass-t-mmerstranda",
    name: "Tømmerstranda",
    kind: "Badeplass",
    topics: ["natur"],
    lat: 63.43082746421054,
    lng: 10.534590703157896,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    facts: [
      { id: "tommerstranda-f1", text: "Tømmerstranda er en populær badeplass langs Trondheimsfjorden.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "tommerstranda-f2", text: "Ligger på turstien langs sjøen mellom Grilstadstranda og Hansbakkfjæra.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "park-grillstadfj-ra",
    name: "Grillstadfjæra",
    kind: "Park",
    topics: ["natur"],
    lat: 63.435689555357165,
    lng: 10.502817602366068,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    facts: [
      { id: "grillstadfjaera-park-f1", text: "Grillstadfjæra er et grøntområde i bydelen.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "grillstadfjaera-park-f2", text: "Fint for turer og avkobling i nabolaget, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "badeplass-hansbakkfj-ra",
    name: "Hansbakkfjæra",
    kind: "Badeplass",
    topics: ["natur"],
    lat: 63.430947417096775,
    lng: 10.541044956774194,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    facts: [
      { id: "hansbakkfjaera-f1", text: "Hansbakkfjæra er en populær badeplass langs Trondheimsfjorden.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "hansbakkfjaera-f2", text: "Østligste badeplassen i strandlinjen som starter ved Grilstadstranda.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "park-ranheim-stasjonspark",
    name: "Ranheim stasjonspark",
    kind: "Park",
    topics: ["natur"],
    lat: 63.42838733789473,
    lng: 10.53466899263158,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    facts: [
      { id: "stasjonspark-f1", text: "Ranheim stasjonspark er et grøntområde i bydelen.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "stasjonspark-f2", text: "Fint for turer og avkobling i nabolaget, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },
  {
    id: "outdoor-estenstadmarka-reppe",
    name: "Estenstadmarka (inngang Reppe)",
    kind: "Turområde",
    topics: ["natur"],
    lat: 63.415,
    lng: 10.556,
    provenance: "documented",
    sourceIds: ["src-placy-lokalkunnskap"],
    note: "Inngang til marka; selve marka strekker seg videre sør.",
    facts: [
      { id: "estenstadmarka-f1", text: "Estenstadmarka starter rett sør for boligområdene, med turstier videre til Estenstadhytta, Lavollen og Stokkbekken.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
      { id: "estenstadmarka-f2", text: "Har 40 km merkede stier og 60 km skiløyper.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-04-17" },
    ],
  },

  /* ---------- Kollektiv ---------- */
  {
    id: "bus-anders-s-yseths-veg",
    name: "Anders Søyseths veg bussholdeplass",
    kind: "Bussholdeplass",
    topics: ["kollektiv"],
    lat: 63.432548,
    lng: 10.510515,
    provenance: "documented",
    sourceIds: ["src-entur"],
    facts: [
      { id: "bus-anders-soyseth-f1", text: "Anders Søyseths veg er en registrert bussholdeplass (NSR:StopPlace:60259) i Entur, Nasjonalt stoppestedsregister.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-06-05" },
      { id: "bus-anders-soyseth-f2", text: "Én av flere bussholdeplasser i gangavstand fra boligfeltet på Ranheim.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-06-05" },
    ],
  },
  {
    id: "entur-NSR-StopPlace-60261",
    name: "Skonnertvegen bussholdeplass",
    kind: "Bussholdeplass",
    topics: ["kollektiv"],
    lat: 63.433588,
    lng: 10.508181,
    provenance: "documented",
    sourceIds: ["src-entur"],
    facts: [
      { id: "bus-skonnertvegen-f1", text: "Skonnertvegen er en registrert bussholdeplass (NSR:StopPlace:60261) i Entur, Nasjonalt stoppestedsregister.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-07-06" },
      { id: "bus-skonnertvegen-f2", text: "Én av flere bussholdeplasser i gangavstand fra boligfeltet på Ranheim.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-07-06" },
    ],
  },
  {
    id: "bus-ranheim-idrettsplass",
    name: "Ranheim idrettsplass bussholdeplass",
    kind: "Bussholdeplass",
    topics: ["kollektiv"],
    lat: 63.427812,
    lng: 10.523133,
    provenance: "documented",
    sourceIds: ["src-entur"],
    facts: [
      { id: "bus-idrettsplass-f1", text: "Ranheim idrettsplass er en registrert bussholdeplass (NSR:StopPlace:41650) i Entur, Nasjonalt stoppestedsregister.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-06-10" },
      { id: "bus-idrettsplass-f2", text: "Én av flere bussholdeplasser i gangavstand fra boligfeltet på Ranheim.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "bus-strindfjordvegen",
    name: "Strindfjordvegen bussholdeplass",
    kind: "Bussholdeplass",
    topics: ["kollektiv"],
    lat: 63.435254,
    lng: 10.505792,
    provenance: "documented",
    sourceIds: ["src-entur"],
    facts: [
      { id: "bus-strindfjordvegen-f1", text: "Strindfjordvegen er en registrert bussholdeplass (NSR:StopPlace:60260) i Entur, Nasjonalt stoppestedsregister.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-04-07" },
      { id: "bus-strindfjordvegen-f2", text: "Én av flere bussholdeplasser i gangavstand fra boligfeltet på Ranheim.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-04-07" },
    ],
  },
  {
    id: "entur-NSR-StopPlace-33",
    name: "Ranheim stasjon",
    kind: "Togstasjon",
    topics: ["kollektiv"],
    lat: 63.427978,
    lng: 10.534298,
    provenance: "documented",
    sourceIds: ["src-entur", "src-placy-lokalkunnskap"],
    facts: [
      { id: "ranheim-stasjon-f1", text: "Ranheim stasjon er en registrert togstasjon (NSR:StopPlace:33) i Entur, Nasjonalt stoppestedsregister.", provenance: "documented", sourceIds: ["src-entur"], checkedAt: "2026-07-06" },
      { id: "ranheim-stasjon-f2", text: "Ranheim er en av få bydeler i Trondheim med egen togstasjon, ifølge lokalkunnskapen.", provenance: "documented", sourceIds: ["src-placy-lokalkunnskap"], checkedAt: "2026-07-06" },
    ],
  },

  /* ---------- Mat og kafé ---------- */
  {
    id: "google-ChIJGe_PpX8wbUYRZIqtZ99Y0M0",
    name: "Restaurant Romantica",
    kind: "Restaurant",
    topics: ["mat"],
    lat: 63.4282611,
    lng: 10.519549,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Ranheimsvegen 165, Ranheim",
    website: "https://www.romantica.no/",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJGe_PpX8wbUYRZIqtZ99Y0M0",
    image: { src: "https://lh3.googleusercontent.com/place-photos/AJRVUZPRD9-A0Egva8VALT_OKBS9xMAA28gqfF6Fj7lJYyEQSClVt7VcmKLo7gE431bb6-YFp_l_6h9YbAd3fEf88iw8ZfpECgfFpBLQX_RXUgyKYdrvwHB-FR2NoV15ugGyTftvJC9ZGfKEwoW17A=s4800-w800", alt: "Restaurant Romantica", kind: "photo", credit: "Google" },
    openingHours: [
      "mandag: 14:00–23:00",
      "tirsdag: 14:00–23:00",
      "onsdag: 14:00–23:00",
      "torsdag: 14:00–23:00",
      "fredag: 14:00–23:00",
      "lørdag: 14:00–23:00",
      "søndag: 13:00–23:00",
    ],
    facts: [
      { id: "romantica-f1", text: "Restaurant Romantica er en pizzeria på Ranheim med trofaste gjester.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "romantica-f2", text: "Fast nabolagsrestaurant for mange familier i bydelen, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "google-ChIJR_8fGNwxbUYRlksBDIfRT-Q",
    name: "Chopsticks Horizont",
    kind: "Restaurant",
    topics: ["mat"],
    lat: 63.4273594,
    lng: 10.522095,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Ranheimsvegen 175, Trondheim",
    website: "https://chopsticksrestaurant.no/",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJR_8fGNwxbUYRlksBDIfRT-Q",
    image: { src: "https://lh3.googleusercontent.com/place-photos/AJRVUZNpsW9txgud40Ad0npqI5v3RJ4_TttzZ7oe_OUS9IezcUC30QY-lDkTBb5D9CbKNRS9Xjs7eG_mvSiMMJjpWoC3mqDkgfgTbloC-Mbr-1qIchCXAsCVwK-AATaOyM-nz6d1pyLR3UnDOGz5dQ=s4800-w800", alt: "Chopsticks Horizont", kind: "photo", credit: "Google" },
    openingHours: [
      "mandag: 14:00–22:00",
      "tirsdag: 14:00–22:00",
      "onsdag: 14:00–22:00",
      "torsdag: 14:00–22:00",
      "fredag: 14:00–22:00",
      "lørdag: 14:00–22:00",
      "søndag: 13:00–22:00",
    ],
    facts: [
      { id: "chopsticks-f1", text: "Chopsticks Horizont er en restaurant i Ranheim-området.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "chopsticks-f2", text: "Ligger i Ranheimsvegen 175, i nærheten av Restaurant Romantica.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
    ],
  },
  {
    id: "google-ChIJ3UeeRKcxbUYRiW4pdqjXjfU",
    name: "Flipper Kafe",
    kind: "Kafé",
    topics: ["mat"],
    lat: 63.4384117,
    lng: 10.507351,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Strindfjordvegen 40, Ranheim",
    website: "http://flipperkafe.no/",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ3UeeRKcxbUYRiW4pdqjXjfU",
    openingHours: [
      "mandag: 11:00–20:00",
      "tirsdag: 11:00–23:00",
      "onsdag: 11:00–23:00",
      "torsdag: 11:00–23:00",
      "fredag: 11:00–00:00",
      "lørdag: 11:00–00:00",
      "søndag: 11:00–20:00",
    ],
    facts: [
      { id: "flipper-kafe-f1", text: "Flipper Kafe er en lokal kafé med hjemmelaget mat i Ranheim-området.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
      { id: "flipper-kafe-f2", text: "Rolig stopp for lunsj eller kaffe midt i hverdagen, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-07-06" },
    ],
  },
  {
    id: "google-ChIJPY2s9UMxbUYRTbDlR1EVVuQ",
    name: "Dromedar Kaffebar Overvik",
    kind: "Kafé",
    topics: ["mat"],
    lat: 63.4206298,
    lng: 10.5155029,
    provenance: "documented",
    sourceIds: ["src-placy-pool"],
    address: "Presthusvegen 45, Ranheim",
    mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJPY2s9UMxbUYRTbDlR1EVVuQ",
    image: { src: "https://lh3.googleusercontent.com/places/ANXAkqEt5AAea4pIQkdCBkgYG5HCnOKIpwsuF7lac4jJG1m1hp4MaMD6yw4v8GBU7OjePSsUSMfGrFKXPt2N7Gb09vUXKlah1WpRMv4=s4800-w800", alt: "Dromedar Kaffebar Overvik", kind: "photo", credit: "Google" },
    facts: [
      { id: "dromedar-f1", text: "Dromedar Kaffebar Overvik er Overviks egen kaffebar, med adresse Presthusvegen 45.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "dromedar-f2", text: "Perfekt for en rolig start på dagen, ifølge stedsbeskrivelsen.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
      { id: "dromedar-f3", text: "Google Business-profilen viser stedet som midlertidig stengt.", provenance: "documented", sourceIds: ["src-placy-pool"], checkedAt: "2026-06-10" },
    ],
  },
];

export const BOLIG_FIXTURE: BoligFixture = {
  version: 1,
  house: {
    id: "house-ranheim-eksempel",
    title: "Enebolig på Ranheim",
    addressLabel: "Eksempelvegen 12, 7053 Ranheim · fiktiv eksempelbolig",
    provenance: "example",
    lat: 63.4318,
    lng: 10.5165,
    intro: "En enebolig i et etablert boligfelt mellom fjorden og Ranheim sentrum. Boligen er et eksempel; stedene rundt er ekte.",
    image: { src: "/illustrations/bolig-ranheim-enebolig-v1.jpg", alt: "Illustrasjon av en enebolig med hage i et boligfelt på Ranheim", kind: "illustration", credit: "Placy-illustrasjon. Viser ikke en faktisk bolig." },
    facts: [
      { id: "house-type", text: "Enebolig fra 1978 med tre soverom og kjeller. Eksempeldata.", provenance: "example", sourceIds: [] },
      { id: "house-plot", text: "Tomt på om lag 700 kvadratmeter med hage mot sør. Eksempeldata.", provenance: "example", sourceIds: [] },
    ],
  },
  topics: [
    {
      topic: "dagligvare",
      text: "Hverdagen på Ranheim er samlet langs aksen mellom Grilstad og Ranheim sentrum, med dagligvare, apotek og nærbutikk der folk beveger seg til daglig. Grilstad-platået er bydelens tyngdepunkt for daglige ærend, og Olderdalen dekker den østlige delen.",
      provenance: "documented",
      sourceIds: ["src-placy-lokalkunnskap"],
    },
    {
      topic: "barn",
      text: "Ranheim er bygget for barnefamilier, med barnehager, lekeplasser og skolevei som premiss i utbyggingen. Ranheim skole ligger sentralt i bydelen, og barnehagedekningen strekker seg fra Grilstadfjæra til Presthus. Mellom skole, idrettspark og fjære ligger mye av en barndom i gangavstand.",
      provenance: "documented",
      sourceIds: ["src-placy-lokalkunnskap"],
    },
    {
      topic: "natur",
      text: "Fjorden ligger tett på Ranheim, med en sammenhengende rekke badeplasser og fjæreområder fra Grilstadstranda via Tømmerstranda til Hansbakkfjæra, bundet sammen av turstien langs sjøen. Sørover ligger Estenstadmarka med turterreng og skiløyper rett fra boligfeltene.",
      provenance: "documented",
      sourceIds: ["src-placy-lokalkunnskap"],
    },
    {
      topic: "kollektiv",
      text: "Ranheim har egen togstasjon, med lokaltog mot Trondheim S og østover mot Værnes uten bytte. Busstilbudet dekker boligfeltene langs både fjæra og høydedraget.",
      provenance: "documented",
      sourceIds: ["src-placy-lokalkunnskap"],
    },
    {
      topic: "mat",
      text: "Mat-tilbudet på Ranheim er nabolagets eget: kafeer ved fjæra, ferske bakervarer, og pizza- og sushisteder for hverdagskveldene. Det meste ligger i gang- eller sykkelavstand fra boligfeltene, gjerne med fjorden som nærmeste nabo.",
      provenance: "documented",
      sourceIds: ["src-placy-lokalkunnskap"],
    },
  ],
  places: RAW_PLACES.map(p => ({
    ...p,
    walkMinutes: BOLIG_WALK_MINUTES[p.id],
    walkSourceId: BOLIG_WALK_MINUTES[p.id] !== undefined ? "src-mapbox-walk" : undefined,
  })),
  seller: [
    { id: "seller-grilstadstranda", topics: ["natur", "selger"], text: "Vi har gått ned til Grilstadstranda nesten hver sommerkveld, bare noen minutter fra døra.", provenance: "example" },
    { id: "seller-skolevei", topics: ["barn"], text: "Barna har hatt lekeplassen i Hulderveien som sitt faste sted, og vi har aldri bekymret oss for skoleveien til Ranheim skole.", provenance: "example" },
    { id: "seller-handling", topics: ["dagligvare"], text: "Jeg handler stort sett på Extra Grilstad, og går innom Rosenborg Bakeri for ferskt brød i helgene.", provenance: "example" },
    { id: "seller-toget", topics: ["kollektiv", "selger"], text: "Jeg tar ofte toget fra Ranheim stasjon til jobb i sentrum, det er en rolig start på dagen.", provenance: "example" },
    { id: "seller-fredagspizza", topics: ["mat"], text: "Fredagspizza fra Restaurant Romantica er en fast tradisjon i familien.", provenance: "example" },
    { id: "seller-marka", topics: ["natur"], text: "Om vinteren går vi rett opp i Estenstadmarka fra enden av gata, med ski på beina.", provenance: "example" },
    { id: "seller-ro", topics: ["selger"], text: "Det jeg kommer til å savne mest er roen, og at alt vi trenger i hverdagen ligger så nær.", provenance: "example" },
    { id: "seller-idrettshallen", topics: ["barn"], text: "Vi har brukt Ranheimshallen mye, både til håndballtrening og bursdagsfeiring.", provenance: "example" },
  ],
  unknowns: [
    { id: "unknown-skolekrets", topics: ["barn"], question: "Hvilken skolekrets tilhører boligen?", answer: "Nærmeste skole er ikke automatisk boligens skolekrets. Trondheim kommune avgjør skoletilhørighet.", sourceIds: ["src-trondheim-kommune-skole"] },
    { id: "unknown-barnehageopptak", topics: ["barn"], question: "Er det ledig barnehageplass i nærheten?", answer: "Vi har ikke oversikt over ledig kapasitet. Barnehagefakta viser hvilke barnehager som finnes, ikke opptak akkurat nå.", sourceIds: ["src-barnehagefakta"] },
    { id: "unknown-rutetider", topics: ["kollektiv"], question: "Hvor ofte går bussen og toget herfra?", answer: "Vi oppgir ikke rutetider eller avgangsfrekvens i denne demoen. Entur har oppdaterte avganger for holdeplassene.", sourceIds: ["src-entur"] },
    { id: "unknown-apningstider", topics: ["dagligvare", "mat"], question: "Hva er åpningstidene akkurat nå?", answer: "Vi viser ikke sanntids åpningstider i denne demoen. Sjekk butikkens eller stedets egne kanaler for oppdaterte tider.", sourceIds: [] },
    { id: "unknown-badevann", topics: ["natur"], question: "Hvordan er badevannskvaliteten og temperaturen?", answer: "Vi har ikke målt badevannskvalitet eller temperatur for badeplassene på Ranheim.", sourceIds: [] },
    { id: "unknown-stoy-trafikk", topics: ["selger"], question: "Er det mye støy eller trafikk ved boligen?", answer: "Vi har ingen måling av støy eller trafikk for denne tomten.", sourceIds: [] },
  ],
  sources: [
    { id: "src-placy-pool", label: "Placys stedsdatabase (Google Places-oppslag)", checkedAt: "2026-08-24", kind: "google" },
    { id: "src-nsr", label: "Nasjonalt skoleregister (NSR, Utdanningsdirektoratet)", url: "https://nsr.udir.no/", checkedAt: "2026-09-12", kind: "register" },
    { id: "src-barnehagefakta", label: "Barnehagefakta (Utdanningsdirektoratet)", url: "https://barnehagefakta.no/", checkedAt: "2026-09-12", kind: "register" },
    { id: "src-entur", label: "Entur, Nasjonalt stoppestedsregister", url: "https://stoppested.entur.org/", checkedAt: "2026-09-12", kind: "register" },
    { id: "src-osm", label: "OpenStreetMap", url: "https://www.openstreetmap.org/", checkedAt: "2026-09-12", kind: "osm" },
    { id: "src-placy-lokalkunnskap", label: "Placy Lokalkunnskap Ranheim (kuratert strøkstekst)", checkedAt: "2026-07-06", kind: "placy" },
    { id: "src-mapbox-walk", label: "Målt gangtid fra eksempelboligens punkt (Mapbox Directions)", checkedAt: "2026-09-12", kind: "measured" },
    { id: "src-trondheim-kommune-skole", label: "Trondheim kommune avgjør skoletilhørighet", url: "https://www.trondheim.kommune.no/tema/skole/", checkedAt: "2026-09-12", kind: "web" },
  ],
};

export { RAW_PLACES };
